Mango-Butter/dev-back

- app/src/main/java/com/mangoboss/app/api/controller/auth/AuthController.java
- app/src/main/java/com/mangoboss/app/api/controller/user/UserController.java
- app/src/main/java/com/mangoboss/app/api/facade/auth/AuthFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/user/UserFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/UserRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/auth/AuthService.java
- app/src/main/java/com/mangoboss/app/domain/service/user/UserService.java
- app/src/main/java/com/mangoboss/app/dto/UserInfoResponse.java
- app/src/main/java/com/mangoboss/app/dto/auth/requeset/LoginRequest.java
- app/src/main/java/com/mangoboss/app/dto/auth/requeset/RefreshTokenRequest.java
- app/src/main/java/com/mangoboss/app/dto/auth/requeset/SignUpRequest.java
- app/src/main/java/com/mangoboss/app/infra/persistence/UserRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/user/UserEntity.java
> #3 
- `role != UNASSIGNED`인 경우 `409 Conflict` 예외 발생
- JWT 필터로 인증된 사용자만 요청 가능
> 작업한 부분을 캡처해 보여주면 이해하기 쉬워요
>
> [#3] 회원가입 API 개발

- app/build.gradle
- app/src/main/java/com/mangoboss/app/api/controller/store/StaffStoreController.java
- app/src/main/java/com/mangoboss/app/api/controller/user/UserController.java
- app/src/main/java/com/mangoboss/app/api/facade/store/StaffStoreFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/user/UserFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/StaffRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/staff/StaffService.java
- app/src/main/java/com/mangoboss/app/domain/service/user/UserService.java
- app/src/main/java/com/mangoboss/app/dto/store/StaffJoinRequest.java
- app/src/main/java/com/mangoboss/app/dto/store/StaffJoinResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/StaffRepositoryImpl.java
- app/src/test/java/com/mangoboss/app/domain/service/staff/StaffServiceTest.java
- storage/src/main/java/com/mangoboss/storage/staff/StaffEntity.java
- storage/src/main/java/com/mangoboss/storage/staff/StaffJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/user/UserEntity.java
> [#9] 알바생은 초대코드/초대링크를 사용하여 매장에 등록할 수 있다.

- app/src/main/java/com/mangoboss/app/api/controller/store/BossStoreController.java
- app/src/main/java/com/mangoboss/app/api/facade/store/BossStoreFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/common/exception/GlobalExceptionHandler.java
- app/src/main/java/com/mangoboss/app/domain/service/store/StoreService.java
- app/src/main/java/com/mangoboss/app/dto/store/request/AttendanceMethodUpdateRequest.java
- app/src/main/java/com/mangoboss/app/dto/store/request/AttendanceSettingsRequest.java
- app/src/main/java/com/mangoboss/app/dto/store/request/GpsRegisterRequest.java
- app/src/main/java/com/mangoboss/app/dto/store/response/AttendanceSettingsResponse.java
- app/src/main/java/com/mangoboss/app/dto/store/response/GpsSettingsResponse.java
- app/src/main/java/com/mangoboss/app/dto/store/response/QrCodeResponse.java
- app/src/test/java/com/mangoboss/app/domain/service/store/StoreServiceTest.java
- storage/src/main/java/com/mangoboss/storage/store/StoreEntity.java
> #14
> 사장은 원하는 방식으로 출근/퇴근 인증 방식을 선택할 수 있다(gps, qr, 둘 다). (5-1)
- 출퇴근 인증 방식 설정, 조회 API 개발
- QR 설정 조회, 재발급 API 개발
- GPS 설정 조회, 변경 API 개발
> 작업한 부분을 캡처해 보여주면 이해하기 쉬워요
> [#14] 사장은 원하는 방식으로 출근/퇴근 인증 방식을 선택할 수 있다(gps, qr, 둘 다)

- app/src/main/java/com/mangoboss/app/api/controller/schedule/BossScheduleController.java
- app/src/main/java/com/mangoboss/app/api/controller/staff/BossStaffController.java
- app/src/main/java/com/mangoboss/app/api/facade/schedule/BossScheduleFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/staff/BossStaffFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/RegularGroupRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/ScheduleRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/RegularGroupRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/ScheduleRepositoryImpl.java
- app/src/main/resources/application-dev.yml
- app/src/main/resources/application-test.yml
- app/src/main/resources/data.sql
- app/src/test/java/com/mangoboss/app/domain/service/schedule/ScheduleServiceTest.java
- storage/src/main/java/com/mangoboss/storage/schedule/RegularGroupEntity.java
- storage/src/main/java/com/mangoboss/storage/schedule/ScheduleJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/store/StoreEntity.java
> [#7] 사장은 알바생들의 출퇴근 일정을 삭제할 수 있다.

- app/src/main/java/com/mangoboss/app/api/controller/staff/BossStaffController.java
- app/src/main/java/com/mangoboss/app/api/facade/staff/BossStaffFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/StaffRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/StoreRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/UserRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/staff/StaffService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/StaffRepositoryImpl.java
- app/src/main/resources/data.sql
- storage/src/main/java/com/mangoboss/storage/staff/StaffJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/store/StoreJpaRepository.java
> #18
---
> 다른 페이지에서 알바생들 선택할 때 조회할 알바생들 목록 간단조회 개발
---
> [#18] 알바생들의 목록 간단조회 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/schedule/BossScheduleController.java
- app/src/main/java/com/mangoboss/app/api/facade/schedule/BossScheduleFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/staff/BossStaffFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
- app/src/main/java/com/mangoboss/app/dto/schedule/request/ScheduleCreateRequest.java
- app/src/main/java/com/mangoboss/app/dto/schedule/request/ScheduleUpdateRequest.java
- app/src/test/java/com/mangoboss/app/domain/service/schedule/ScheduleServiceTest.java
- storage/src/main/java/com/mangoboss/storage/schedule/ScheduleEntity.java
- 스케줄 수정 기능 개발
- 스케줄 추가 비즈니스 로직 수정에 따른 refactor
- 에러수정
> #7
---
---
> [#7] 스케줄 수정 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/dashboard/BossDashboardController.java
- app/src/main/java/com/mangoboss/app/api/facade/dashboard/BossDashboardFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/AttendanceRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/RegularGroupRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/attendance/AttendanceService.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
- app/src/main/java/com/mangoboss/app/dto/dashboard/response/StaffAttendanceCountResponse.java
- app/src/main/java/com/mangoboss/app/dto/dashboard/response/StaffAttendanceSummaryResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/AttendanceRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/RegularGroupRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/attendance/AttendanceJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/attendance/projection/StaffAttendanceCountProjection.java
- storage/src/main/java/com/mangoboss/storage/schedule/RegularGroupJpaRepository.java
> [#30] 사장이 알바생 근무 요일, 근태 요약 조회 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/store/BossStoreController.java
- app/src/main/java/com/mangoboss/app/api/controller/store/StaffStoreController.java
- app/src/main/java/com/mangoboss/app/api/facade/store/BossStoreFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/store/StaffStoreFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/StoreRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/store/StoreService.java
- app/src/main/java/com/mangoboss/app/dto/store/response/BossStoreInfoResponse.java
- app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreInfoResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/StoreRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/store/StoreJpaRepository.java
> [#33] 알바생 매장 정보 조회 API 개발

- app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
- app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
> [#24] 근로계약서 알바생 서명 완료시 스케줄 자동 생성 로직 구현

- app/src/main/java/com/mangoboss/app/api/controller/contract/BossContractController.java
- app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/ContractTemplateRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
- app/src/main/java/com/mangoboss/app/domain/service/contract/ContractTemplateService.java
- app/src/main/java/com/mangoboss/app/dto/contract/request/ContractTemplateCreateRequest.java
- app/src/main/java/com/mangoboss/app/dto/contract/request/ContractTemplateData.java
- app/src/main/java/com/mangoboss/app/dto/contract/request/ContractTemplateUpdateRequest.java
- app/src/main/java/com/mangoboss/app/dto/contract/response/ContractTemplateDetailResponse.java
- app/src/main/java/com/mangoboss/app/dto/contract/response/ContractTemplateResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/ContractTemplateRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/contract/ContractTemplate.java
- storage/src/main/java/com/mangoboss/storage/contract/ContractTemplateJpaRepository.java
> [#22] 근로계약서 템플릿 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/contract/StaffContractController.java
- app/src/main/java/com/mangoboss/app/api/facade/contract/StaffContractFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/ContractRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
- app/src/main/java/com/mangoboss/app/dto/contract/response/StaffContractListResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/ContractRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/contract/ContractJpaRepository.java
> [#42] 알바생 근로계약서 목록 조회 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/document/BossDocumentController.java
- app/src/main/java/com/mangoboss/app/api/facade/document/BossDocumentFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
> [#47] 사장이 보관된 서류를 조회, 삭제, 다운로드하는 API 개발

- app/src/main/java/com/mangoboss/app/api/controller/attendance/BossAttendanceController.java
- app/src/main/java/com/mangoboss/app/api/controller/contract/BossContractController.java
- app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/ContractRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
- app/src/main/java/com/mangoboss/app/dto/contract/response/ContractSummaryResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/ContractRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/contract/ContractEntity.java
- storage/src/main/java/com/mangoboss/storage/contract/ContractJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/contract/ContractStatus.java
> [#47] 사장이 알바생 근로계약서 목록 조회 API 개발

- app/src/main/java/com/mangoboss/app/api/controller/document/StaffDocumentController.java
- app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
- app/src/main/java/com/mangoboss/app/dto/document/response/MyDocumentStatusResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/document/DocumentJpaRepository.java
> [#52] 알바생 본인이 제출한 서류 목록과 제출 상태 조회 API 개발

- app/src/main/java/com/mangoboss/app/api/controller/calendar/BossCalendarController.java
- app/src/main/java/com/mangoboss/app/api/controller/calendar/StaffCalendarController.java
- app/src/main/java/com/mangoboss/app/api/facade/calendar/BossCalendarFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/calendar/StaffCalendarFacade.java
> [#58] 캘린더에서 알바생이 다른 알바생 전체 근무 일정 조회 API 개발 

- app/src/main/java/com/mangoboss/app/api/facade/document/StaffDocumentFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/document/DocumentService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/document/DocumentJpaRepository.java
> [#39] 서류 업로드 시 중복 업로드 방지 로직 추가 

- app/src/main/java/com/mangoboss/app/api/controller/attendance/StaffAttendanceController.java
- app/src/main/java/com/mangoboss/app/api/facade/attendance/StaffAttendanceFacade.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
> [#61] 알바생 본인 근태 기록 월별 조회, 특정 근태 기록 상세 조회 

- app/src/main/java/com/mangoboss/app/api/controller/payroll/BossPayrollController.java
- app/src/main/java/com/mangoboss/app/api/controller/payroll/ConfirmEstimatedPayrollRequest.java
- app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/EstimatedPayrollRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/PayrollRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/PayrollSettingRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/EstimatedPayroll.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollService.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollSettingService.java
- app/src/main/java/com/mangoboss/app/domain/service/staff/StaffService.java
- app/src/main/java/com/mangoboss/app/dto/payroll/request/ConfirmEstimatedPayrollRequest.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollEstimatedResponse.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollSimpleResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/EstimatedPayrollRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/PayrollRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/PayrollSettingRepositoryImpl.java
- app/src/main/resources/data.sql
- batch/src/main/java/com/mangoboss/batch/domain/service/TransferExecutor.java
- storage/src/main/java/com/mangoboss/storage/attendance/AttendanceEntity.java
- storage/src/main/java/com/mangoboss/storage/payroll/PayrollAmount.java
- storage/src/main/java/com/mangoboss/storage/payroll/PayrollEntity.java
- storage/src/main/java/com/mangoboss/storage/payroll/PayrollJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/payroll/PayrollSettingEntity.java
- storage/src/main/java/com/mangoboss/storage/payroll/WithholdingType.java
- storage/src/main/java/com/mangoboss/storage/payroll/estimated/EstimatedJpaPayrollRepository.java
- storage/src/main/java/com/mangoboss/storage/payroll/estimated/EstimatedPayrollEntity.java
- storage/src/main/java/com/mangoboss/storage/staff/StaffEntity.java
> [#37] 알바생 예상 급여 확인 및 자동 송금용 엔티티 로직 추가

- app/src/main/java/com/mangoboss/app/api/controller/payroll/BossPayrollController.java
- app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/PayrollRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollService.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollSettingService.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollEstimatedResponse.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollSimpleResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/PayrollRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/payroll/PayrollJpaRepository.java
> [#37] 확정된 급여 조회 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/payroll/BossPayrollController.java
- app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/TransferAccountRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollSettingService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/TransferAccountRepositoryImpl.java
> [#37] 사장 계좌 삭제 기능 개발

- .github/workflows/cd.yml
- app/src/main/java/com/mangoboss/app/api/controller/task/StaffTaskController.java
- app/src/main/java/com/mangoboss/app/api/facade/task/BossTaskFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/task/StaffTaskFacade.java
- app/src/main/java/com/mangoboss/app/common/constant/S3FileType.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/common/util/S3FileManager.java
- app/src/main/java/com/mangoboss/app/domain/repository/TaskLogRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/TaskRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/task/TaskService.java
- app/src/main/java/com/mangoboss/app/dto/s3/response/UploadPreSignedUrlResponse.java
- app/src/main/java/com/mangoboss/app/dto/task/request/TaskCheckRequest.java
- app/src/main/java/com/mangoboss/app/dto/task/response/AssignedTaskResponse.java
- app/src/main/java/com/mangoboss/app/dto/task/response/TaskLogDetailResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/TaskLogRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/TaskRepositoryImpl.java
- app/src/main/resources/application-dev.yml
- app/src/main/resources/application-test.yml
- storage/src/main/java/com/mangoboss/storage/task/TaskJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/task/TaskLogEntity.java
- storage/src/main/java/com/mangoboss/storage/task/TaskLogJpaRepository.java
> [#71] 알바생은 필요 시 체크리스트에 사진을 첨부하여 완성할 수 있다.

- app/src/main/java/com/mangoboss/app/api/controller/task/BossTaskController.java
- app/src/main/java/com/mangoboss/app/api/controller/task/StaffTaskController.java
- app/src/main/java/com/mangoboss/app/api/facade/task/BossTaskFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/task/StaffTaskFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/TaskLogRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/TaskRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/task/TaskService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/TaskLogRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/TaskRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/task/TaskLogJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/task/TaskRoutineJpaRepository.java
> [#70] 사장은 업무 체크리스트의 진행 상황을 상시 조회가 가능하다.

- app/src/main/java/com/mangoboss/app/api/controller/task/StaffTaskController.java
- app/src/main/java/com/mangoboss/app/api/controller/workreport/StaffWorkReportController.java
- app/src/main/java/com/mangoboss/app/api/facade/task/StaffTaskFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/workreport/StaffWorkReportFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/WorkReportRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/workreport/WorkReportService.java
- app/src/main/java/com/mangoboss/app/dto/workreport/request/WorkReportCreateRequest.java
- app/src/main/java/com/mangoboss/app/infra/persistence/WorkReportRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/metadata/S3FileType.java
- storage/src/main/java/com/mangoboss/storage/workreport/WorkReportJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/workreport/WorkReportTargetType.java
> [#81] 알바생 보고사항 작성, 보고사항 조회/상세조회 기능 개발

- .github/workflows/cd.yml
- .gitignore
- batch/build.gradle
- batch/src/main/java/com/mangoboss/batch/infra/FcmInitializer.java
- batch/src/main/resources/application.yml
> ex) #82 
-[x] 기능 추가  
-[ ] 기능 삭제  
-[ ] 버그 수정  
-[x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
---
---
> [#82] FCM 연동

- app/src/main/java/com/mangoboss/app/api/controller/payroll/StaffPayrollController.java
- app/src/main/java/com/mangoboss/app/api/facade/payroll/StaffPayrollFacade.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/PayrollSettingForStaffResponse.java
- app/src/test/java/com/mangoboss/app/domain/service/schedule/ScheduleServiceTest.java
> [#92] 알바생 매장 급여 설정 정보 조회 기능 개발

- app/src/main/java/com/mangoboss/app/api/controller/staff/StaffStaffController.java
- app/src/main/java/com/mangoboss/app/api/facade/staff/StaffStaffFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollService.java
- app/src/main/java/com/mangoboss/app/domain/service/staff/StaffService.java
- storage/src/main/java/com/mangoboss/storage/payroll/PayrollEntity.java
- storage/src/main/java/com/mangoboss/storage/staff/StaffEntity.java
> [#96] 알바생 계좌 삭제 기능 개발

- .github/workflows/cd.yml
- app/src/main/java/com/mangoboss/app/api/controller/user/UserController.java
- app/src/main/java/com/mangoboss/app/api/facade/user/UserFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/DeviceTokenRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/NotificationRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/notification/DeviceTokenService.java
- app/src/main/java/com/mangoboss/app/dto/user/request/DeviceTokenRegisterRequest.java
- app/src/main/java/com/mangoboss/app/infra/persistence/DeviceTokenRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/NotificationRepositoryImpl.java
- batch/src/main/java/com/mangoboss/batch/notification/FcmInitializer.java
- batch/src/main/java/com/mangoboss/batch/notification/FcmSender.java
- batch/src/main/java/com/mangoboss/batch/notification/NotificationHandler.java
- batch/src/main/java/com/mangoboss/batch/notification/NotificationRepository.java
- batch/src/main/java/com/mangoboss/batch/notification/NotificationRepositoryImpl.java
- batch/src/main/java/com/mangoboss/batch/notification/NotificationScheduler.java
- batch/src/main/java/com/mangoboss/batch/notification/NotificationService.java
- batch/src/main/resources/application.yml
- storage/src/main/java/com/mangoboss/storage/notification/DeviceTokenEntity.java
- storage/src/main/java/com/mangoboss/storage/notification/DeviceTokenJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationEntity.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationType.java
- storage/src/main/java/com/mangoboss/storage/notification/SendStatus.java
> [#82] Notification 도메인 생성 및 알림 배치 발송 로직 구현

- .github/workflows/cd.yml
- app/src/main/java/com/mangoboss/app/api/controller/notification/BossNotificationController.java
- app/src/main/java/com/mangoboss/app/api/controller/notification/StaffNotificationController.java
- app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/notification/BossNotificationFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/notification/StaffNotificationFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/NotificationRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/notification/NotificationService.java
- app/src/main/java/com/mangoboss/app/dto/notification/response/NotificationResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/NotificationRepositoryImpl.java
- app/src/main/resources/application-dev.yml
- app/src/main/resources/application-test.yml
- storage/src/main/java/com/mangoboss/storage/notification/NotificationEntity.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationJpaRepository.java
> [#24] 근로계약서 생성 후 알바생에게 서명 요청 푸시 알림 전송 기능 구현

- app/src/main/java/com/mangoboss/app/api/controller/TestController.java
- app/src/main/java/com/mangoboss/app/api/controller/store/StaffStoreController.java
- app/src/main/java/com/mangoboss/app/api/facade/store/StaffStoreFacade.java
- app/src/main/java/com/mangoboss/app/common/util/PdfGenerator.java
- app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreItemResponse.java
- app/src/main/resources/application-dev.yml
- app/src/main/resources/templates/contract-template.html
- storage/src/main/java/com/mangoboss/storage/attendance/AttendanceEditEntity.java
> [#100] 근로계약서 html 수정 및 매장조회시 staffId 반환

- app/src/main/java/com/mangoboss/app/dto/store/response/StaffStoreInfoResponse.java
> [#100] 매장 정보 조회 response에 알바생 정보 추가

- app/src/main/java/com/mangoboss/app/api/facade/attendance/BossAttendanceFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/attendance/StaffAttendanceFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/contract/BossContractFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/schedule/BossScheduleFacade.java
- app/src/main/java/com/mangoboss/app/api/facade/schedule/StaffScheduleFacade.java
- app/src/main/java/com/mangoboss/app/domain/service/attendance/AttendanceEditService.java
- app/src/main/java/com/mangoboss/app/domain/service/notification/NotificationService.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/SubstituteRequestService.java
- storage/src/main/java/com/mangoboss/storage/attendance/AttendanceEditEntity.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationType.java
- storage/src/main/java/com/mangoboss/storage/schedule/SubstituteRequestEntity.java
> [#104] 근태 변경/대타 요청 알림 추가

- app/src/main/java/com/mangoboss/app/api/controller/store/BossStoreController.java
- app/src/main/java/com/mangoboss/app/api/facade/store/BossStoreFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/AttendanceEditRepository.java
- app/src/main/java/com/mangoboss/app/domain/repository/SubstituteRequestRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/attendance/AttendanceEditService.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/ScheduleService.java
- app/src/main/java/com/mangoboss/app/domain/service/schedule/SubstituteRequestService.java
- app/src/main/java/com/mangoboss/app/dto/schedule/response/SubstituteRequestResponse.java
- app/src/main/java/com/mangoboss/app/dto/store/response/StoreRequestedResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/AttendanceEditRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/SubstituteRequestRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/attendance/AttendanceEditJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/schedule/SubstituteRequestEntity.java
- storage/src/main/java/com/mangoboss/storage/schedule/SubstituteRequestJpaRepository.java
> [#100] 매장의 근태변경 및 대타 요청 수 조회 기능 개발

- admin/src/main/java/com/mangoboss/admin/api/controller/faq/FaqController.java
- admin/src/main/java/com/mangoboss/admin/api/facade/faq/FaqFacade.java
- admin/src/main/java/com/mangoboss/admin/common/exception/CustomErrorInfo.java
- admin/src/main/java/com/mangoboss/admin/domain/repository/FaqRepository.java
- admin/src/main/java/com/mangoboss/admin/domain/service/FaqService.java
- admin/src/main/java/com/mangoboss/admin/dto/faq/request/FaqCreateRequest.java
- admin/src/main/java/com/mangoboss/admin/dto/faq/request/FaqUpdateRequest.java
- admin/src/main/java/com/mangoboss/admin/dto/faq/response/FaqResponse.java
- admin/src/main/java/com/mangoboss/admin/infra/persistence/FaqRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/faq/FaqCategory.java
- storage/src/main/java/com/mangoboss/storage/faq/FaqEntity.java
- storage/src/main/java/com/mangoboss/storage/faq/FaqJpaRepository.java
> [#110] FAQ 등록, 수정, 삭제, 조회 API 개발

- app/build.gradle
- app/src/main/java/com/mangoboss/app/api/controller/TestController.java
- app/src/main/java/com/mangoboss/app/common/exception/GlobalExceptionHandler.java
- app/src/main/resources/application.yml
> feat: 센트리 모니터링 추가 (#109)

- app/src/main/java/com/mangoboss/app/api/controller/payroll/BossPayrollController.java
- app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/domain/repository/PayrollRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/payroll/PayrollService.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/TransferSummaryResponse.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/TransferSummaryStateForResponse.java
- app/src/main/java/com/mangoboss/app/infra/persistence/PayrollRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/infra/persistence/PayrollSettingRepositoryImpl.java
- app/src/main/resources/application-dev.yml
> [#100] 송금 날짜 정보 조회 추가 및 redis tls 설정 추가

- admin/src/main/java/com/mangoboss/admin/domain/repository/SubscriptionRepository.java
- admin/src/main/java/com/mangoboss/admin/domain/service/AdminDashBoardService.java
- admin/src/main/java/com/mangoboss/admin/dto/dashboard/SubscriptionStatisticsResponse.java
- admin/src/main/java/com/mangoboss/admin/infra/persistence/SubscriptionRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/api/controller/billing/BillingController.java
- app/src/main/java/com/mangoboss/app/api/facade/billing/BillingFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/common/util/CardIssuerResolver.java
- app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
- app/src/main/java/com/mangoboss/app/dto/billing/request/BillingRegisterRequest.java
- app/src/main/java/com/mangoboss/app/dto/billing/response/BillingCardInfoResponse.java
- app/src/main/java/com/mangoboss/app/dto/subscription/response/SubscriptionResponse.java
- batch/src/main/java/com/mangoboss/batch/billing/AutoBillingService.java
- batch/src/main/java/com/mangoboss/batch/billing/SubscriptionBillingHandler.java
- batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepository.java
- batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/billing/BillingEntity.java
- storage/src/main/java/com/mangoboss/storage/subscription/PlanType.java
- storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionEntity.java
- storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionJpaRepository.java
> [#122] 구독 관련 코드 변경 

- admin/src/main/java/com/mangoboss/admin/domain/repository/SubscriptionRepository.java
- admin/src/main/java/com/mangoboss/admin/domain/service/AdminDashBoardService.java
- admin/src/main/java/com/mangoboss/admin/dto/dashboard/SubscriptionStatisticsResponse.java
- admin/src/main/java/com/mangoboss/admin/infra/persistence/SubscriptionRepositoryImpl.java
- app/src/main/java/com/mangoboss/app/api/controller/billing/BillingController.java
- app/src/main/java/com/mangoboss/app/api/facade/billing/BillingFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/common/util/CardIssuerResolver.java
- app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
- app/src/main/java/com/mangoboss/app/dto/billing/request/BillingRegisterRequest.java
- app/src/main/java/com/mangoboss/app/dto/billing/response/BillingCardInfoResponse.java
- app/src/main/java/com/mangoboss/app/dto/subscription/response/SubscriptionResponse.java
- app/src/main/resources/application-dev.yml
- app/src/main/resources/application.yml
- app/src/main/resources/data.sql
- batch/src/main/java/com/mangoboss/batch/billing/AutoBillingService.java
- batch/src/main/java/com/mangoboss/batch/billing/SubscriptionBillingHandler.java
- batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepository.java
- batch/src/main/java/com/mangoboss/batch/billing/SubscriptionRepositoryImpl.java
- storage/src/main/java/com/mangoboss/storage/billing/BillingEntity.java
- storage/src/main/java/com/mangoboss/storage/subscription/PlanType.java
- storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionEntity.java
- storage/src/main/java/com/mangoboss/storage/subscription/SubscriptionJpaRepository.java
> release: dev -> main

- app/src/main/java/com/mangoboss/app/api/facade/subscription/SubscriptionFacade.java
- app/src/main/java/com/mangoboss/app/domain/repository/SubscriptionRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/billing/BillingService.java
- app/src/main/java/com/mangoboss/app/domain/service/subscription/SubscriptionService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/SubscriptionRepositoryImpl.java
> [#122] 사장 구독 현황, 결제 수단 없을 때 null DTO 반환 

- app/src/main/java/com/mangoboss/app/api/controller/auth/AuthController.java
- app/src/main/java/com/mangoboss/app/api/facade/auth/AuthFacade.java
- app/src/main/java/com/mangoboss/app/common/exception/CustomErrorInfo.java
- app/src/main/java/com/mangoboss/app/common/util/JwtUtil.java
- app/src/main/java/com/mangoboss/app/domain/service/auth/AuthService.java
- 로그아웃시 refresh-token Redis에 블랙리스트로 보관
> #128
---
---
> [#128] 로그아웃 기능 개발 

- app/src/main/java/com/mangoboss/app/api/facade/workreport/StaffWorkReportFacade.java
- app/src/main/java/com/mangoboss/app/domain/service/notification/NotificationService.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationEntity.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationJpaRepository.java
- storage/src/main/java/com/mangoboss/storage/notification/NotificationType.java
> [#81] 알바생이 사장님에게 보고사항 작성 시 사장님에게 알림 전송 기능 개발 

- app/src/main/java/com/mangoboss/app/api/facade/workreport/StaffWorkReportFacade.java
> [Release] 알바생 보고사항 작성자 정보 잘못 표시되는 버그 수정

- app/src/main/java/com/mangoboss/app/api/facade/payroll/BossPayrollFacade.java
- app/src/main/java/com/mangoboss/app/dto/payroll/response/TransferSummaryResponse.java
> [Release] payroll summary null 에러 해결

- app/src/main/java/com/mangoboss/app/domain/repository/DocumentRepository.java
- app/src/main/java/com/mangoboss/app/domain/service/contract/ContractService.java
- app/src/main/java/com/mangoboss/app/infra/persistence/DocumentRepositoryImpl.java
- app/src/test/java/com/mangoboss/app/domain/service/attendance/context/AttendanceStrategyContextTest.java
- app/src/test/java/com/mangoboss/app/domain/service/attendance/strategy/BothValidationStrategyTest.java
- app/src/test/java/com/mangoboss/app/domain/service/attendance/strategy/GpsValidationStrategyTest.java
- app/src/test/java/com/mangoboss/app/domain/service/attendance/strategy/QrValidationStrategyTest.java
- app/src/test/java/com/mangoboss/app/domain/service/billing/BillingServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/contract/ContractHtmlGeneratorTest.java
- app/src/test/java/com/mangoboss/app/domain/service/contract/ContractServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/contract/ContractTemplateServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/document/DocumentServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/document/RequiredDocumentServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/faq/FaqServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/notification/DeviceTokenServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/notification/NotificationServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/subscription/SubscriptionServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/task/TaskServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/task/context/TaskRoutineStrategyContextTest.java
- app/src/test/java/com/mangoboss/app/domain/service/task/strategy/DailyTaskRoutineGenerationStrategyTest.java
- app/src/test/java/com/mangoboss/app/domain/service/task/strategy/MonthlyTaskRoutineGenerationStrategyTest.java
- app/src/test/java/com/mangoboss/app/domain/service/task/strategy/WeeklyTaskRoutineGenerationStrategyTest.java
- app/src/test/java/com/mangoboss/app/domain/service/user/UserServiceTest.java
- app/src/test/java/com/mangoboss/app/domain/service/workreport/WorkReportServiceTest.java
- app/src/test/resources/templates/contract-template.html
> [test] 테스트 코드 작성

- app/src/main/java/com/mangoboss/app/api/controller/TestController.java
> ex) #이슈번호
-[ ] 기능 추가  
-[ ] 기능 삭제  
-[ ] 버그 수정  
-[ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
---
---
> test: test를 위한 커밋
